menu_app/menu/urls.py
from django.urls import path

from .views import ListMenusPageView, FoldersPageView

app_name = 'menu'

urlpatterns = [
    path('', ListMenusPageView.as_view(), name='list_menus'),
    path('<slug:menu_slug>/', FoldersPageView.as_view(), name='menu'),
]

menu_app/menu_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('menu.urls')),
]

menu_app/menu/models.py
from django.core.exceptions import ValidationError
from django.db import models


class Menu(models.Model):
    slug = models.SlugField(max_length=255, primary_key=True)

    def __str__(self):
        return self.slug

    class Meta:
        ordering = ('slug',)


class Folder(models.Model):
    slug = models.SlugField(max_length=50)
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    menu = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
        related_name='folders'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['menu', 'slug'], name='unique_folder_slug_in_menu'),
        ]

        ordering = ('slug', )

    def clean(self):
        if self.parent and self.parent.menu != self.menu:
            raise ValidationError('Parent menu must eq menu')

    def __str__(self):
        return self.slug

menu_app/menu/views.py
from collections import defaultdict

from django.db.models import Q
from django.http import Http404, HttpResponse, HttpRequest
from django.shortcuts import render
from django.views import View

from .models import Menu, Folder


class ListMenusPageView(View):

    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Render start page with list of menus.
        """
        menus = Menu.objects.all()
        return render(request, 'list_menus.html', {'menus': menus})


class FoldersPageView(View):
    MAIN_NODE = 'root'

    @staticmethod
    def clean_path_nodes(path: list[str]) -> dict[str, str]:
        """
        Make dictionary with pairs (folder_slug, parent_folder_slug).
        For folders with no parent add 'root'.
        """
        path_nodes = {}
        for i in range(1, len(path)):

            # check circles in path
            if path[i] in path_nodes:
                raise Http404
            path_nodes[path[i]] = path[i-1]

        return path_nodes

    def get(self, request: HttpRequest, menu_slug: str) -> HttpResponse:
        """
        Render page with tree menu structure.
        """
        path_string = request.GET.get('path')
        path = [self.MAIN_NODE, ]
        path_nodes = {}
        parent_query = Q(parent=None)
        if path_string:
            parents_slugs = path_string.strip('/').split('/')
            path += parents_slugs
            path_nodes = self.clean_path_nodes(path)
            parent_query = parent_query | Q(parent__slug__in=parents_slugs)

        folders = Folder.objects.filter(
            Q(menu__slug=menu_slug) & parent_query).select_related('parent')

        folder_nodes = defaultdict(list)
        for folder in folders:
            folder_parent = self.MAIN_NODE
            if folder.parent:
                folder_parent = folder.parent.slug

            # check correct folder - parent_folder link
            if path_nodes.get(folder.slug, folder_parent) != folder_parent:
                raise Http404
            folder_nodes[folder_parent].append(folder)

        context = {
            'path': path,
            'folder_nodes': folder_nodes,
            'menu_slug': menu_slug,
        }

        return render(request, 'menu_page.html', context)

menu_app/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8'>
  <title>{% block title %} Title {% endblock %}</title>
  <link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/all.min.css' rel='stylesheet'>
  <style>
    body {
      font-size: 1.3rem;
    }
    ul {
      list-style-type: none;
      padding: 0;
      margin: 0 0 0 .75rem;
    }
  </style>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

menu_app/templates/list_menus.html
{% extends 'base.html' %}

{% block title %} List of menus {% endblock %}

{% block content %}
List of menus
<br>
<br>
<ul>
{% for menu in menus %}
  <li><a href='{% url "menu:menu" menu.slug %}'>{{ menu }}</a></li>
{% endfor %}
</ul>
{% endblock %}

menu_app/templates/menu_page.html
{% extends 'base.html' %}

{% block title %} {{ menu_slug }} {% endblock %}
{% block content %}
  <a href='{% url "menu:list_menus" %}'>Back</a>
  <a href='{% url "menu:menu" menu_slug %}' style='margin-left: 3rem;'>Close all</a>
  <br>
  {{ menu_slug }}
  <br>
  <br>
  {% with p='root' path_to_folder='/'|add:menu_slug|add:'/?path=' %}
    {% include 'menu_tree.html' %}
  {% endwith %}
{% endblock %}

menu_app/templates/menu_tree.html
{% load menu_extras %}

<ul>
  {% if folder_nodes|get:p|length > 0 %}
    {% for folder in folder_nodes|get:p %}
      <li> <a href='{{ path_to_folder|add:folder.slug }}/'><i class='fas fa-folder'></i> {{ folder }}</a>
        {% if folder.slug in path %}
          <ul>
            {% with p=folder.slug path_to_folder=path_to_folder|add:folder.slug|add:'/' %}
              {% include 'menu_tree.html' %}
            {% endwith %}
          </ul>
        {% endif %}
      </li>
    {% endfor %}
  {% else %}
  <li><i><span style='color: gray;'>{{ 'null' }}</span></i></li>
  {% endif %}
</ul>